# -*- coding: utf-8 -*-
"""Day14 LLM transformers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BN0p2yg4f2yUphLS9L2iNi7l07Gk0P3d

#gen ai llm gen ai date- 11 march 2026
"""

# pip install -U transformers accelerate huggingface_hub

from dotenv import load_dotenv
load_dotenv()
import os

import os
from openai import OpenAI

client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=os.environ["HF_TOKEN"],
)

# conversation memory
messages = []
print("Chat started (type 'exit' to stop)\n")
while True:
    user_input = input("Satyam->: ")
    if user_input.lower() == "exit":
        print("Chat ended.")
        break
    messages.append({"role": "user", "content": user_input})
    completion = client.chat.completions.create(
        model="meta-llama/Llama-3.1-8B-Instruct",
        messages=messages
    )
    reply = completion.choices[0].message.content
    print("AI chatbot ->:", reply, "\n")
    messages.append({"role": "assistant", "content": reply})

# practice 1:
#  Scenario: AI‑Powered Email Assistant
# You’re building an email drafting assistant for a corporate team.
# - When a user starts typing:
# “Artificial Intelligence will…”
# - The assistant uses GPT‑2 to auto‑complete the sentence with a coherent continuation.
# - Example output:
# “Artificial Intelligence will transform the way businesses interact with customers,
# enabling faster decisions and personalized experiences.”
from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

print(generator("gen ai is", max_length=30))

# practice 2:
#  Scenario: Game Storyline Generator
# You’re designing a fantasy role‑playing game and need quick ideas for quests and dialogue.
# - The developer types a prompt:
# “The hero enters the ancient forest and discovers…”
# - The GPT‑2 pipeline continues the story:
# “The hero enters the ancient forest and discovers a hidden village where the people whisper of
#  a cursed artifact buried beneath the old ruins.”

# Install transformers if not installed
# !pip install transformers torch

from transformers import pipeline

# Load GPT-2 text generation pipeline
generator = pipeline("text-generation", model="gpt2")

# Game prompt
prompt = "The hero enters the ancient forest and discovers"

# Generate storyline
story = generator(
    prompt,
    max_length=60,
)

# Print result
print("Generated Story:\n")
print(story[0]['generated_text'])

# practice 3:
# Scenario: Research Assistant for Academic Papers
# Imagine you’re building a tool for university researchers who analyze large collections of academic papers.
# - A researcher uploads a sentence:
# “Deep learning models are powerful”
# - Your system uses the BERT tokenizer to break the sentence into smaller units (tokens).

from transformers import AutoTokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
text = "Deep learning models are powerful"
tokens = tokenizer.tokenize(text)
print(tokens)

# practice 4:
# Scenario: Healthcare Chatbot for Patient Queries
# A hospital is developing a chatbot to help patients ask questions about their health.
# - A patient types:
# “Deep learning models are powerful” (or in practice, something like “I have chest pain and shortness of breath”).
# - The chatbot uses the BERT tokenizer to break the sentence into tokens:
from transformers import BertTokenizer

# Load BERT tokenizer
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")

# Patient query
text = "I have chest pain and shortness of breath"
# Tokenize the sentence
tokens = tokenizer.tokenize(text)

# Print results
print("Original Sentence:",text)
print("\nTokens:",tokens)

# practice 5:
# Scenario: Exploring Creativity in AI Writing
# A university professor is running a workshop on creative writing with AI.
# - The professor gives students the prompt:
# “The future of Artificial Intelligence”
# - The system uses GPT‑2 to generate continuations of the sentence.
# To demonstrate how temperature affects creativity:
# - With temperature = 0.2 (low randomness), the output is more predictable and conservative, e.g.:
# “The future of Artificial Intelligence will bring advancements in healthcare, education, and business.”

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = "The future of Artificial Intelligence"

print(generator(prompt, max_length=40, temperature=0.2))
print(generator(prompt, max_length=40, temperature=0.8))

# practice 6:
#  Scenario: Scriptwriting Assistant for Film Production
# A film studio is experimenting with AI to help writers brainstorm dialogue and plot ideas.
# - The writer provides the prompt:
# “The future of Artificial Intelligence”
# - The system generates two versions of the continuation:
# - Temperature = 0.2 (low randomness)
# Output is more predictable and formal, e.g.:
# “The future of Artificial Intelligence will improve industries, enhance productivity, and reshape education.”
# → This is useful for serious, factual narration in a documentary script.
# - Temperature = 0.8 (higher randomness)
# Output is more imaginative and varied, e.g.:
# “The future of Artificial Intelligence dances with uncertainty, weaving stories of machines dreaming and societies reborn.”
# → This is perfect for creative dialogue or speculative sci‑fi storytelling
# Install if needed
# !pip install transformers torch

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = "The future of Artificial Intelligence"

# Low randomness
print("Temperature = 0.2\n")
print(generator(prompt, max_length=40, temperature=0.2))
# High randomness
print("\nTemperature = 0.8\n")
print(generator(prompt, max_length=40, temperature=0.8))

# practice: 7
# Scenario: AI‑Powered News Headline Generator
# A digital media company wants to help journalists brainstorm headlines and opening lines for articles.
# - The system asks the journalist to enter a prompt (e.g., “Enter a prompt: The future of Artificial Intelligence”).
# - The GPT‑2 model then generates a continuation of the text, up to 50 tokens.
# - Example output:
# “The future of Artificial Intelligence will reshape industries, redefine creativity, and challenge
#  our understanding of human potential.”

from transformers import pipeline

generator = pipeline("text-generation", model="gpt2")

prompt = input("Enter a prompt: ")

output = generator(prompt, max_length=30)

print(output[0]["generated_text"])

# practice 8:
# Scenario: Student Brainstorming Tool for Essay Writing
# A college student is struggling to start their essay.
# - The system prompts them:
# “Enter a prompt:”
# - The student types:
# “The impact of technology on education”
# - The GPT‑2 model generates a continuation up to 50 tokens, for example:
# “The impact of technology on education has transformed classrooms, enabling online learning,
# personalized study plans, and global collaboration among students.”

from transformers import pipeline

# Load GPT-2 text generator
generator = pipeline("text-generation", model="gpt2")

# Ask student for prompt
prompt = input("Enter a prompt: ")

# Generate essay continuation
print(generator(prompt, max_length=50))

# practice 9:
# Scenario: AI Model Evaluation in a Startup
# A startup is building an AI‑powered content assistant to help marketers draft product descriptions.
# - The team wants to compare two models: GPT‑2 (larger, more expressive) and DistilGPT‑2 (smaller, faster, distilled version).
# - They use the same prompt:
# “Artificial Intelligence will transform”
# - The system generates two outputs:
# - GPT‑2 Output
# Longer, more detailed continuation, e.g.:
# “Artificial Intelligence will transform industries by automating processes, enhancing creativity, and
# reshaping how humans interact with technology.”
# → Richer but slower to run.
# - DistilGPT‑2 Output


from transformers import pipeline

gpt2 = pipeline("text-generation", model="gpt2")
distilgpt2 = pipeline("text-generation", model="distilgpt2")

prompt = "Artificial Intelligence will transform"

print("GPT2:", gpt2(prompt, max_length=40))
print("DistilGPT2:", distilgpt2(prompt, max_length=40))

# practice 10:
# Scenario: Educational Tool for Classroom Learning
# A high school teacher is introducing students to AI‑powered writing assistants.
# - The teacher wants to show how different models produce different styles of text.
# - They use the same prompt:
# “Artificial Intelligence will transform”
# - The system generates two outputs:
# - GPT‑2 Output
# More elaborate continuation, e.g.:
# “Artificial Intelligence will transform the way societies function, influencing education, healthcare, and the future of human creativity.”
# → Great for showing students how AI can generate rich, detailed ideas.
# - DistilGPT‑2 Output
# Shorter, faster continuation, e.g.:
# “Artificial Intelligence will transform our daily lives.”
# → Useful for demonstrating concise summaries.

from transformers import pipeline

# Load GPT-2 model
generator_gpt2 = pipeline("text-generation", model="gpt2")

# Load DistilGPT-2 model
generator_distilgpt2 = pipeline("text-generation", model="distilgpt2")

# Prompt used by the teacher
prompt = "Artificial Intelligence will transform"

print("GPT-2 Output:\n")
print(generator_gpt2(prompt, max_length=40))
print("\nDistilGPT-2 Output:\n")
print(generator_distilgpt2(prompt, max_length=40))